version: '3'

services:

  app:
    build: .
    volumes:
      - .:/home/python/app #sincroniza com o diretorio de trabalho, tudo o que fizer na minha maquina sera mandado para o container
    ports:
      - 8000:8000
      